### ISSUE TITLE
Failed to load Series ERROR

### ISSUE THREAD

**Issue by Maltavius** [comixed/comixed#1701] opened 2023-10-05 10:58 UTC
**Describe The Bug**
A clear and concise description of what the bug is. Please include as much detail as possible.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:

1. Go to 'Hamburger menu'
2. Click on 'Series'
3. Se error pop up

**Expected Behavior**
I expect the Series from the 2000+ comics I have currently imported to be visible.

**ComiXed Runtime Environment**

 - [ ] Windows
 - [X] Linux (any distro)
 - [ ] MacOS
 - [X] Docker (if so, please select the host OS)

**Browser (If A Web Issue)**

 - [ ] Chrome
 - [X ] Firefox
 - [ ] Safari
 - [ ] Other (if so, please provide a name)

**ComiXed Build Detail:**

The code was built from a branch named 1a8f1f6c746c12400f4c2f0389c30aec6d947fa8
The code was built on 2023-09-30T13:34:40.000+00:00.
Code was built on a machine named undefined.
The code was marked with a Build version of undefined.
The latest commit hash on the source branch is undefined.
build-details.label.comit-time
Commit Message
Commit was created by undefined <undefined>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch undefined
build-details.label.jdbcUrl

**Screenshots**
![bild](https://github.com/comixed/comixed/assets/10133945/d687e2ca-9669-4b95-909e-4b8ac090a230)

There are at least a couple of Series in the All comics section
![bild](https://github.com/comixed/comixed/assets/10133945/eb97c520-c856-41d6-82f1-57ca2fe6a24e)

**Additional Context**

**Comment by mcpierce** [comment] 2023-10-05 13:43
@Maltavius By any chance, were you importing comics at the time this happened?

**Comment by Maltavius** [comment] 2023-10-05 13:54
Unfortunately, no.

I did this between imports

**Comment by mcpierce** [comment] 2023-10-05 13:58
> Unfortunately, no. I did this between imports

kk - are there possibly any comics that aren't scraped, or that are missing metadata? I'm thinking (I'll investigate this weekend) the problem is due to the backend trying to get the list of series and finding a comic that has an empty series name causing it to fail.

Either way, I'll have it fixed shortly and put out an update within the week.

**Comment by mcpierce** [comment] 2023-10-07 12:25
@Maltavius Found the issue, and have fixed it and verified it locally. I'll put out a new release (v1.6.2) next weekend with the fix in it.

If you would, once you've verified things are working for you, please close this ticket. And thanks again for reporting the issue!

**Closed as completed** 2023-11-04 16:27 UTC
Labels: bug, critical, collection
