### ISSUE TITLE
Use a single "Fetch" action to scrape multiple issues from the same series and volume.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#150] opened 2020-02-20 02:25 UTC
When scraping multiple issues from the same series and volume, CX should require the user to select the first issue, and then use that information to match the remaining issues.

A pre-condition of this function is that the comics all have the appropriate information in the series, volume and issue fields.

For example if I'm scraping the entire Liberty Meadows series (excluding specials etc.), I should be prompted to select the appropriate match for the first issue being scrapped - CX should then use that information to match the remaining issues.

If an issue number cannot be matched, the user should be prompted to manally chose the appropriate issue.

**Comment by mcpierce** [comment] 2020-02-23 22:48
I think this is a duplicate of #25.

**Comment by bareheiny** [comment] 2020-02-23 23:19
Ah..yes.  It is a duplicate.

And I even commented on the existing issue, so there's not really any excuse for my creating a new one...

**Comment by mcpierce** [comment] 2021-07-03 14:53
Closing this as a duplicate.

**Closed as completed by mcpierce** 2021-07-03 14:53 UTC
