### ISSUE TITLE
Selections not being cleared when returning to the Comics \ Library view.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#286] opened 2020-06-02 03:52 UTC
Select a comic, and open it.

Return to the Comics page (either via the bread crumb menu, or the Comics \ Library menu actions.

Note that the selected comic is still selected.

This is problematic when opening a single comic, and then returning to the library to preform an action on multiple comics.  It is possible for a user to forget that a comic is selected - which can result in an inadvertant / unwanted deletion.

Ideally, every time the Comics page is returned to all selections would be cleared.

**Comment by mcpierce** [comment] 2020-06-02 14:14
Closing this as not a bug. Quoting from the comixed-dev mailing list:

>For the selection issue, I think it's an expectation issue and not a bug: you don't need to select a 
> comic to open it, you can just right click on a comic, selected or not, and open it from the popup 
> menu. Viewing a comic and going back to the library view won't clear the selection since no 
> operation was done on the selected comics. This lets your look at a single comic's details when 
> building a selection without affecting your previous selections.
>
> We could definitely enhance the delete dialog to make it easier for the admin to see what they're 
> about to delete. But I don't think the scenario you described is a bug: that's how the app is 
> intended to work.

**Closed as completed by mcpierce** 2020-06-02 14:14 UTC
Labels: wontfix

**Comment by bareheiny** [comment] 2020-06-02 21:30
And you learn something new everyday.  I'd been working under the assumption that I had to select a comic before opening it.

**Comment by mcpierce** [comment] 2020-06-02 23:14
@bareheiny That used to be the case before 0.6. It changes when I made the context menu a central component. :smile:
