### ISSUE TITLE
Importer fails on second bookmark

### ISSUE THREAD

**Issue by SkaryMonk** [comixed/comixed#166] opened 2020-03-01 13:34 UTC
When importing my ComicDB.xml from ComicRack, the import fails when trying to create the second bookmark because of a key violation.
Error Message: 

> Unique index or primary key violation: "CONSTRAINT_DE_INDEX_9 ON PUBLIC.USER_BOOKMARKS(BOOK) VALUES (102, 102)"; SQL statement: insert into user_bookmarks (id, book, mark, user_id) values (null, ?, ?, ?) [23505-197]

**To Reproduce**
1. Try importing a ComicDB.xml with --user specified.
2. Wait for it to fail
3. See error

**Expected behavior**
The import should correctly do the bookmark IDs and finish the import.

**Desktop (please complete the following information):**
 - ComiXed version: 0.6.0-0
 - OS: Windows 10
 - Browser name: Firefox
 - Browser version: 73.0

** ComiXed Build Detail **
Source Branch | develop
Build Hostname | Pickled-Punk
Built On | Feb 27, 2020, 3:57:13 PM
Version | 0.6.0-0
Commit Hash | bf3967108d3dc37230b980fa36b9823b720f182d
Committer Name | Darryl L. Pierce (mcpierce@users.noreply.github.com)
Time Of Last Commit | Feb 24, 2020, 12:35:52 AM
Commit Message | [Issue #108] Add an option to override the image cache directory. (#146)
Built From Uncommitted Code? | false
Remote Origin | https://github.com/comixed/comixed.git

**Comment by mcpierce** [comment] 2020-03-01 17:07
I think I see what the issue is there: the user_bookmarks table has a uniqueness constraint on the book column. I think that's a mistake in intent: there should be a uniqueness constraint for a user and a book and not for just a book.

**Comment by mcpierce** [comment] 2020-03-01 18:13
@SkaryMonk I'm pushing a change for this. Would you mind testing it and seeing if it solves the problem for you? If so, please respond here and close the ticket.

I'm going to backport this change to a 0.5.1 release so that users of the current release can also benefit from the fix if it works.

**Comment by SkaryMonk** [comment] 2020-03-02 07:15
That was exactly it! Or if it wasn't, your commits still fixed it. :)

**Comment by SkaryMonk** [comment] 2020-03-02 07:22
Wait, it might be worth noting that I am now getting a lot of 
`WARN 13532 --- [ Jarvis-ComiXed] o.h.h.internal.ast.QueryTranslatorImpl   : HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!`
after building with these updates.

**Comment by SkaryMonk** [comment] 2020-03-02 07:55
I accidentally specified a non-existing user for the successful import. It seems the issue persists when I use an existing user. :(

**Comment by mcpierce** [comment] 2020-03-02 12:48
@SkaryMonk That output in the logs i normal and isn't related to the issue you reported. Also, I just realized that you never actually got the code: since it's in a PR it doesn't get automatically included in a build. I'm going to go ahead and promote the PR and the next build will have the fix in it. Then please test it and, if it works, close this ticket.

**Comment by mcpierce** [comment] 2020-03-07 19:53
Closing this as fixed.

@SkaryMonk if you see the error pop up again please feel free to respond on this issue.

**Closed as completed by mcpierce** 2020-03-07 19:53 UTC
Labels: bug, critical, bookmark
