### ISSUE TITLE
Add a limit to the number of comics to find during import

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#4] opened 2019-11-21 01:24 UTC
**Is your feature request related to a problem? Please describe.**
When importing comics, I would like to set a limit on the number of comics to find before returning the set of results.

**Comment by bareheiny** [comment] 2020-06-30 10:53
Duplicate of #34 (or vice versa)?

**Comment by mcpierce** [comment] 2020-06-30 12:18
@bareheiny No, this issue is about limiting the number of results returned when importing comics. #34 is about limiting the number of results returned from ComicVine during scraping.

**Closed as completed** 2020-07-02 14:11 UTC
Labels: importing, feature
