### ISSUE TITLE
CreateProcess not a valid Win32 application

### ISSUE THREAD

**Issue by hitnrun30** [comixed/comixed#68] opened 2019-11-25 13:41 UTC
**Describe the bug**
Im trying to install the application but keep running into the CreateProcess error=193, %1 is not a valid Win32 application

**To Reproduce**
Installing on windows with 64bit

**Expected behavior**
no errors when running mvn clean package

**Screenshots**

**Desktop (please complete the following information):**
 - Latest version
 - OS: Windows 10

** ComiXed Build Detail **

**Additional context**
I have Maven installed and functioning, 64bit Node.js and 64bit jdk

**Comment by mcpierce** [comment] 2019-11-25 13:53
@hitnrun30 What's the command line you're using to launch the app?

You mention having Maven and node.js installed: are you trying to build the code and run it? If so, from which branch?

**Comment by hitnrun30** [comment] 2019-11-26 15:00
From the main branch, I am just trying to build per the instructions on the main page.

**Comment by mcpierce** [comment] 2019-11-26 15:07
@hitnrun30 Try building from the develop branch rather than master. There's been a lot of changes since the last time we merged up to master and I'm not sure that code is worth trying out now.

Also, what's your exact command line for trying to build?

**Comment by hitnrun30** [comment] 2019-11-26 15:19
I did pull from the develop branch.  all i do is put in 
mvn clean install 
and I get the below error.  I then did some googling and then noticed that you have 2 profiles in the pom.xml, if i delete the dev profile, it will compile.

[ERROR] Failed to execute goal com.cosium.code:maven-git-code-format:1.37:install-hooks (install-formatter-hook) on project comixed: java.io.IOException: Cannot run program "C:\HTPC\Maven\bin\..\bin\mvn": CreateProcess error=193, %1 is not a valid Win32 application -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by hitnrun30** [comment] 2019-11-26 15:24
OK, let me edit, if I remove the line
activeByDefault>true</activeByDefault
from the dev profile, it will install.

**Comment by mcpierce** [comment] 2019-11-26 15:26
@hitnrun30 Okay, previous you had said you were building "[f]rom the main branch". I just want to be clear what code you're working with on your end.

You shouldn't need to delete any profiles. The only thing that the dev profile does is to disable checking the Java code format before compiling (the other profile, for CI, enforces our coding standard and fails builds if the code doesn't meet that standard). Removing "true" only makes maven run without any profiles active, which is disabling the **maven-git-code-format** plugin.

The error message you're getting isn't due to the code in our repository. I think the issue is that some local binary on your end is not correct. See the first line of the error message you shared:

```
[ERROR] Failed to execute goal com.cosium.code:maven-git-code-format:1.37:install-hooks (install-formatter-hook) on project comixed: java.io.IOException: Cannot run program "C:\HTPC\Maven\bin..\bin\mvn": CreateProcess error=193, %1 is not a valid Win32 application -> [Help 1]
```

You have some binary or script named "mvn" under **C:\HTPC\Maven\bin** that isn't a Windows binary (where is says "Cannot run program" in the error). CX isn't putting anything in that directory, that's something on your side.

**Comment by hitnrun30** [comment] 2019-11-26 15:31
I got ya, but I downloaded Maven and is installed and works, I verified the version, in that same folder is a mvn file with no extension and a mvn.cmd, should I just delete the one with no extension and retry?

**Comment by mcpierce** [comment] 2019-11-26 16:26
@hitnrun30 You can try that. I'm not really sure about Maven on Windows and what it delivers. But doing a quick google search on the error message produced [this issue](https://github.com/eirslett/frontend-maven-plugin/issues/487) with the suggestion to do the following:

```
mvn dependency:purge-local-repository -DmanualInclude=com.github.eirslett:node
mvn clean package
```

**Comment by hitnrun30** [comment] 2019-11-26 17:02
I did that, but it didn't work, right now im trying it out, it finally installed when I removed the Active by default value.  I was hoping it was more of a Mylar replacement.
Good luck

**Comment by mcpierce** [comment] 2019-11-26 17:07
@hitnrun30 Hrm, I'll check it out on my Windows box since it sounds like the maven plugin might have issues with Windows. It runs fine on Linux and the Mac for me.

**Comment by jmcrfp** [comment] 2019-11-27 00:28
I'm having the same issue, this looks like a bug in maven-git-code-format, that calls up mvn in the wrong way in windows. With version 1.36 of the plugin I don't have this issue. Maybe we could rollback to that version.

My workaround for the moment was to stop using gitbash or cmd and start compiling in WSL 2 (https://docs.microsoft.com/en-us/windows/wsl/install-win10)

**Comment by mcpierce** [comment] 2019-11-27 01:37
@jmcrfp @hitnrun30 One of my team mates at work uses a Windows machine for development. We use the same plugin there and he has no issues. We're using the same profile setup as here.

That said, we're using 1.36 at work and 1.37 here, specifically because the maintainer added code to throttle the output for Travis. So if going back to 1.36 works, I can do that. But could one of you file a bug with the plugin so they can fix the issue? Thanks.

**Comment by mcpierce** [comment] 2019-11-27 12:57
@hitnrun30 The fix was merged. Can you update your code and check if you can build now? And, if so, please close this ticket. Thanks.

**Comment by jmcrfp** [comment] 2019-11-27 23:30
The fix solved it. I also opened a issue for it https://github.com/Cosium/maven-git-code-format/issues/31
Closing this issue

**Closed as completed by jmcrfp** 2019-11-27 23:30 UTC
Labels: triage
