### ISSUE TITLE
Some comics still in unprocessed state after import completed

### ISSUE THREAD

**Issue by jimbodoken-byte** [comixed/comixed#528] opened 2020-10-18 23:02 UTC
**NOTE: If this involves a pre-release version of ComiXed and not a release, then please send an email to the mailing list rather than creating an issue here.**

**Describe the bug**
Imported a large folder (14k files) and after the import completed, some comics are still in an unprocessed state. They still have the circling graphic, and cannot be selected for re-processing or removal

**To Reproduce**
1. Import folder of files
2. Wait (days) for processing to finish. Not sure if this mattered, but the machine was rebooted a couple times during processing.
3. 32 files still not proccessed
4. I could find no way to re-process or remove the files

**Expected behavior**
Files should all be processed

**Screenshots**
![image](https://user-images.githubusercontent.com/73083150/96387899-795d4900-1173-11eb-8c33-6c63a6d7efb7.png)

**Desktop (please complete the following information):**
 - ComiXed version 0.7.0-1
 - OS: Ubuntu 18.04
 - Browser name Firefox
 - Browser version 81.0.2 (64-bit)

** ComiXed Build Detail **

Source Branch | c27d5f55f8a5beec0622078d7de8b746c42341a5
-- | --
Build Hostname | fv-az128
Built On | Oct 5, 2020, 3:06:22 PM
Version | 0.7.0-1
Commit Hash | c27d5f55f8a5beec0622078d7de8b746c42341a5
Committer Name | Darryl L. Pierce ()
Time Of Last Commit | Oct 5, 2020, 12:50:25 AM
Commit Message | Changed the release version to 0.7.0-1 [#496]
Built From Uncommitted Code? | true
Remote Origin |  
JDBC Connection URL | jdbc:h2:file:~/.comixed/comixed;create=true

**Additional context**
I doubt it's relevant, but the machine is a virtual running on proxmox.

**Comment by mcpierce** [comment] 2020-10-19 12:02
@jimbodoken-byte Were you able to capture a log during the import? The most likely reason this failed was some unexpected exception was thrown while the ProcessingComicWorkerTask ran, which would have been logged by Jarvis. With that info I can fix the problem.

**Comment by mcpierce** [comment] 2020-10-19 12:12
@jimbodoken-byte I took a look in the code and found at least one possible fix. Would you mind testing a build and see if you can reproduce the issue? You could potentially reduce the time needed to verify things by trying to import only the comics that failed previously. And, if you could, please capture a log so we can see what may have caused it to fail should it have issues still.

**Comment by jimbodoken-byte** [comment] 2020-10-20 22:13
I've pulled some logs. I grep'd to find entries for Thunderbolts v1 Faith In Monsters, one of the comics that failed to process. 

[grep.log](https://github.com/comixed/comixed/files/5411846/grep.log)
[comixed.log.2020-10-13.111.log](https://github.com/comixed/comixed/files/5411842/comixed.log.2020-10-13.111.log)
[comixed.log.2020-10-18.170.log](https://github.com/comixed/comixed/files/5411843/comixed.log.2020-10-18.170.log)
[comixed.log.2020-10-18.172.log](https://github.com/comixed/comixed/files/5411844/comixed.log.2020-10-18.172.log)
[comixed.log.2020-10-19.1.log](https://github.com/comixed/comixed/files/5411845/comixed.log.2020-10-19.1.log)

If there's a better way to find the right logs, let me know.

I'd be happy to try testing a build.

**Comment by mcpierce** [comment] 2020-10-21 12:25
The latest development build should have the initial fix I'm proposing.

Now, that said, I think I see at least one reason why you're having issues importing comics. Right now CX only handles RAR, ZIP and 7Z archived files. I see in the comixed.log.2020-10-13.111.log file the following:

```
org.comixedproject.task.model.WorkerTaskException: Failed to load comic
	at org.comixedproject.task.model.AddComicWorkerTask.startTask(AddComicWorkerTask.java:100) ~[comixed-tasks-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.task.model.AddComicWorkerTask$$FastClassBySpringCGLIB$$46736851.invoke(<generated>) ~[comixed-tasks-0.7.0-1.jar!/:0.7.0-1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.comixedproject.task.model.AddComicWorkerTask$$EnhancerBySpringCGLIB$$7df4386a.startTask(<generated>) ~[comixed-tasks-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.task.runner.TaskManager.lambda$runTask$0(TaskManager.java:71) ~[comixed-tasks-0.7.0-1.jar!/:0.7.0-1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
Caused by: org.comixedproject.handlers.ComicFileHandlerException: No archive adaptor defined for type: octet-stream
	at org.comixedproject.handlers.ComicFileHandler.loadComicArchiveType(ComicFileHandler.java:186) ~[comixed-adaptors-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.task.model.AddComicWorkerTask.startTask(AddComicWorkerTask.java:84) ~[comixed-tasks-0.7.0-1.jar!/:0.7.0-1]
	... 15 common frames omitted
```

CX uses a library called Tika to identify what a file is, such as archives and image files. And Tika's saying this file's type is "octet-stream", which just means a generic array of bytes. 

Later, in the same log, I see:
```
javax.imageio.IIOException: Unsupported Image Type
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1139) ~[na:na]
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1110) ~[na:na]
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468) ~[na:na]
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1363) ~[na:na]
	at org.comixedproject.loaders.ImageEntryLoader.loadContent(ImageEntryLoader.java:58) ~[comixed-adaptors-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.adaptors.archive.AbstractArchiveAdaptor.processContent(AbstractArchiveAdaptor.java:234) ~[comixed-adaptors-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.adaptors.archive.ZipArchiveAdaptor.loadAllFiles(ZipArchiveAdaptor.java:93) ~[comixed-adaptors-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.adaptors.archive.ZipArchiveAdaptor.loadAllFiles(ZipArchiveAdaptor.java:46) ~[comixed-adaptors-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.adaptors.archive.AbstractArchiveAdaptor.doLoadComic(AbstractArchiveAdaptor.java:155) ~[comixed-adaptors-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.adaptors.archive.AbstractArchiveAdaptor.loadComic(AbstractArchiveAdaptor.java:135) ~[comixed-adaptors-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.task.model.ProcessComicWorkerTask.startTask(ProcessComicWorkerTask.java:82) ~[comixed-tasks-0.7.0-1.jar!/:0.7.0-1]
	at org.comixedproject.task.runner.TaskManager.lambda$runTask$0(TaskManager.java:71) ~[comixed-tasks-0.7.0-1.jar!/:0.7.0-1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
```

from the archive "Hulk_Contents.cbz" when processing some of the image files within it. Tika's identifying them as JPEG images, but when Java tries to load them each image is coming back as invalid and not as JPEG-encoded data.

This seems to be the recurring set of problems. When processing another file identified as a ZIP archive, the contents of the file ultimately failed and caused Java (not CX) to throw a ZipException (filename: Amazing Spider-Man v1 #281.cbz, also #268, #275, etc).

A little later there is a corrupt file: Daredevil V2 002.cbz

It's possible that these files were corrupted by whatever tool was used to manage them previously (I've had ComicRack do this to me, it would crash while updating a file in the background and the file would get corrupted).  So while the fix I added will address some issues, it won't be able to fix the problems in these cases that caused the files to not import since the failures are caused by bad data.

What I think we can do to help though is to add a feature to show files that couldn't be processed during import. That way the user can see specifically what's not importing and why. I've created #530 to provide this feature with the 0.8 release.

**Comment by jimbodoken-byte** [comment] 2020-10-26 02:50
OK, I see where some of those files could have lead to that. I've had them for quite a long time and some could have been corrupted through moving, some may not have been fully formed to begin with.

It wasn't possible to remove the files as they are in the 'processing' state (can't open right-click menu)

I downloaded 0.7.0-3 and ran that. I still can't re-import the files, I think because it still sees them as being in the database.

I'm not sure where the database is located. I found some .db files in ~/.comixed that I tried stopping program, renaming, then restarting program. Didn't seem to change anything, so I'm assuming these are not the correct database files.

Where is the database stored? I'll try renaming it and running the import on just those files.

**Comment by mcpierce** [comment] 2020-10-26 14:54
@jimbodoken-byte If you don't override the database, then by default the file is ~/.comixed/comixed.*.db (on Windows, it's in c:\users\[username]\.comixed). 

I would imagine that it's going to block you from re-importing those comics currently since it's still trying to process them. When #530 is implemented then an admin will be able to delete such files, or else fix the issue and try re-importing.

If you're savvy with H2, you can open the database and try deleting the entries from the comics and pages tables for the comics that aren't importing as a short-term solution until we get #530 merged into develop.

**Comment by jimbodoken-byte** [comment] 2020-10-27 01:39
I've confirmed that the updates in 0.7.0-3 allowed import and processing to complete. Some of the previous failures succeeded completely, others were not added at all, but the web log entries show the error now, which is great.

**Comment by mcpierce** [comment] 2021-02-27 15:47
@jimbodoken-byte I'm going to close this since, as of the last comment four months ago, things appeared to be working. If the error comes up again in the next release please open a new bug and we can try readdressing things.

**Closed as completed by mcpierce** 2021-02-27 15:47 UTC
Labels: bug, importing, triage
