### ISSUE TITLE
When using Multi-Comic Scraping I get "A general error has occurred" 

### ISSUE THREAD

**Issue by cjil** [comixed/comixed#2181] opened 2024-11-03 01:52 UTC
**Describe The Bug**
When using multi-comic scraping, after the results have been returned, clicking on a series gives the error "a general error has occurred". 

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Go go "Unscraped Comics"
2. Select a couple of comics
3. Click ""Selected Comics > Scrape Metadata"
4. Go to "Multi-comic scraping"
5. Select a comic
6. Click "Scrape metadata" (note metadata source is set as "ComicVineMetadataAdaptor" by default as this is the only adaptor I have installed)
7. Click on a selected volume
8. A popup appears at the top of the page stating that a "general error has occurred" and it will not let me proceed with importing the metadata.

**Expected Behavior**
The scraped volume is displayed allowing me to scrape the issue data, or if an error has occurred a more detailed explanation to help identify why there is an error 

**ComiXed Runtime Environment**
 - [X] Docker (Synology NAS)

**Browser (If A Web Issue)**
 - [X] Other (Floorp)

**ComiXed Build Detail:**
 The code was built from a branch named ab9f23175db635cc904afcc5c09caf7200f95d7b
The code was built on October 22, 2024 at 11:50:54 AM GMT+11.
Code was built on a machine named fv-az1144-789.
The code was marked with a Build version of 2.2.1-2.
The latest commit hash on the source branch is ab9f23175db635cc904afcc5c09caf7200f95d7b.
This commit was created on October 22, 2024 at 11:38:32 AM GMT+11.
Commit Message
Changed the release version to v2.2.1-2 [#2157]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:postgresql://db:5432/comixed
Using Java 17.0.2+8-86 (Oracle Corporation) running on Linux v4.4.302+ (amd64) 

**Additional Context**
The problem appears to come and go. While I have been struggling with it for the past couple of hours, right now as I am writing this bug report it is working fine. Note while I was getting the errors, I did check my API usage on ComicVine and it was only showing 30ish uses on the /search endpoint and nothing else.

**Comment by mcpierce** [comment] 2024-11-08 12:56
@cjil Please feel free to close this ticket if the issue is fixed.

**Closed as completed** 2024-11-09 00:23 UTC
Labels: bug, metadata, critical, needs-reply
